### ISSUE TITLE
Integration doesn't work for me

### ISSUE THREAD

**Issue by jdschuitemaker** [msvisser/remeha_home#1]
Hi,

The integration does not work for me. I am seeing this error after adding the integration in Settings:

```
Logger: homeassistant.config_entries
Source: config_entries.py:424
First occurred: 15:12:15 (1 occurrences)
Last logged: 15:12:15

Config entry 'Remeha Home' for remeha_home integration not ready yet; Retrying in background
```

My installation was manual as HACS could not find it. Maybe I should have added your GIT to HACS first? Anyway, I uploaded the files to the correct folder (I assume) and after a reboot I was able to select it in the add integrations page. After providing email address and password, it was added to the installed integrations, but with an error.

I am trying to use this with a eTwist thermostat from Remeha. I have been using [this](https://github.com/freitdav/BDRthermostatHA) integration, until it stopped working a couple of days ago. That integration requires you to pair the integration with the thermostat. The pairing code can be retrieved from the thermostat itself.

Maybe this integration is not for me, because it is lacking the pairing currently?

**Comment by msvisser** [comment]
Hi,

I just started working on this integration a week ago, but great to see that there is interest. Are you using the Remeha Home app for your eTwist thermostat, or the older eTwist app? This integration only works for thermostats that are paired with the Remeha Home app.

Currently there is no way to do the pairing from the integration, you should pair your thermostat with the app first. After this you should be able to log in and see your "climate zones".

The integration is not currently in the HACS repository yet, so you can add it as a custom repository, but the goal is to get it included in the default repository.

- Michiel

**Comment by jdschuitemaker** [comment]
Ah, now I understand why it doesn't work. My eTwist is not yet ready for the new Home Connect App. I am still waiting for it to be moved.

Thank you for clarifying.

**Comment by gdesmott** [comment]
I got confused by this as well. May be worth mentioning in the README?

Thanks for working on this integration!

**Comment by msvisser** [comment]
I have added an extra note to the readme. Hopefully it is clearer now.
