### ISSUE TITLE
Feature request - thermostat current temperature as a seperate sensor

### ISSUE THREAD

**Issue by HanSyt** [msvisser/remeha_home#13]
Goed morning, the watertemperature sensor is working great. 

I would like to setup a history graph with 3 values:
current outdoor temperature (works - available)
current water temperature (works - available)
current thermostat temperature

The current thermostat temperature is available as attribute to the GTW16 implementation. However, Home Assistant does not recognize it a a sensor so no history data is available. This was the same in the old plugin, so I am using a separate temperature sensor for this.
Is it possible to have an optional sensor in the plugin that has the current temperature?

Thanks,

**Comment by dynasticorpheus** [comment]
Why not use a template sensor?

**Comment by HanSyt** [comment]
Did not think of that, made this in the template editor under sensors, does what i is supposed to do, thanks

-platform: template
    sensors
      Livingroom_Thermostat_Temp:
      friendly_name: "Thermostat Livingroom Current Temperature"
      unit_of_measurement: "°C"
      value_template: "{{ state_attr('climate.gtw_16','current_temperature') }}"

**Comment by HanSyt** [comment]
Solved by template
