### ISSUE TITLE
Lost wifi connection on Etwist

### ISSUE THREAD

**Issue by BobPuts** [msvisser/remeha_home#14]
Hi There,

Wondering if there are more users having problems with the Etwist Thermostat that is saying Connection problems cannot connect to server. Have now disabled the remeha_home integration to test it.

Regards,
Bob

**Comment by msvisser** [comment]
I have not seen any issues with my eTwist thermostat losing connection. Occasionally I see a minute or two where the thermostat becomes unavailable in Home Assistant, but it always reconnects.

**Comment by BobPuts** [comment]
strange it seems to be an issue since they connect me to the new app. Already stopt the remeha_home to check if this is the problem but it isn't

**Comment by Luc4Piccinini** [comment]
I had to replace one right after installation a couple of years ago, while now it loses wifi connection and even re-entering the password after a while it disconnects again!
this has been going on for 2 weeks now. It disconnects, I select the network again and put the password and then it disconnects again!
