### ISSUE TITLE
Feature request: Add software version of Thermostat

### ISSUE THREAD

**Issue by BobPuts** [msvisser/remeha_home#15]
Hi there,

Is it possible to get the software version of the thermostat in Home Assistant?

Kind regards,
Bob Puts

**Comment by msvisser** [comment]
There is an API for getting the software and hardware version of the thermostat, so it should be possible.

How would you like to have access to the version information? I can possibly add it as version information on the device in Home Assistant, or I can create a sensor for it.

**Comment by dynasticorpheus** [comment]
IMHO version information should be added to the device as this is the default. So would do that anyway regardless of also exposing via sensor.

**Comment by msvisser** [comment]
I have added the version information of the thermostat to the corresponding climate zone. Please let me know if it works correctly for everyone. Currently there is no sensor with the version information. If there is a need for it, I can add it in later.

See [v0.1.9](https://github.com/msvisser/remeha_home/releases/tag/v0.1.9).
