### ISSUE TITLE
Invalid email address and/or password

### ISSUE THREAD

**Issue by matt7py** [msvisser/remeha_home#17]
Hi,

I am trying to connect to my Remeha using my credentials, but it keeps refusing my login. I am positive that my credentials are correct. By the way, I have been using a BDR thermostat, which requires a pairing number, and it has been working perfectly.

![Remeha](https://user-images.githubusercontent.com/120527800/226900344-ec6e11f8-4b43-4ab7-ae3e-04a2cbbc1cc1.jpg)

Regards,
Matt

**Comment by msvisser** [comment]
Are you sure your thermostat has been migrated to the new __Remeha Home__ app? If it is, you should be able to use the same credentials as you would use with the app.

If you are sure you can use the new app and it still does not work in Home Assistant, let me know.

**Comment by msvisser** [comment]
@matt7py If this is still an issue let me know. For now I'm closing this issue.
