### ISSUE TITLE
Binary sensors for hotWater / Heating status? 

### ISSUE THREAD

**Issue by geezer78** [msvisser/remeha_home#18]
Hi,

Thanks for this great integration!
I would like to know if there's a way to show when the cv is heating water for the hot water tap.
I guess a binary sensor "hotWater" or something like that?

also I noticed that I can see in the charts that there is an indicator showing that the burner is on for heating, but we don't seem to have a (binary) sensor for that either.

**Comment by msvisser** [comment]
I have added a sensor for the hot water zone status. This sensor currently directly displays the state as reported by the API, but I can possibly change it to a binary sensor in the future.

You should be able to extract the burner state for heating from the climate entity, but if that is not possible I can also add in a binary sensor for that.

See [v0.1.9](https://github.com/msvisser/remeha_home/releases/tag/v0.1.9).

**Comment by geezer78** [comment]
Hi msvisser,

Thanks for the super fast action!
I've tested 0.1.9 just now and can confirm the API burner state for hot water is now displayed!
I can definitely extract a binary sensor for both burner states, but maybe it can be helpful for others.
Thanks again for your hard work!

**Comment by lierenaar** [comment]
Great work msvisser,
I’m really happy with this integration. Is there a status flag that indicates that the boiler is on for heating up the rooms? I only wants to switch on the pumps when there is production.
Thanks in advance

**Comment by msvisser** [comment]
In versions v0.1.10 and v0.1.11 I have added binary sensors for climate zone heating active and hot water heating active. These sensors are disabled by default, but can be enabled when you want to use them.

I think this solves all of the feature requests, therefore I'm closing the issue. If there is anything else that you would like to have please let me know.
