### ISSUE TITLE
API documentation request

### ISSUE THREAD

**Issue by vipial1** [msvisser/remeha_home#23]
First of all, congrats for this amazing integration. It works like a charm.

I did a similar integration (https://github.com/vipial1/BAXI_thermostat) time ago, focused only in Baxi thermostats. It was able to control the thermostat and get some consumption data as well.

And why I say "It WAS"?...because since Baxi updated the app to use same backend than Remeha, the integration is not working anymore. API is completely different now.

I have been able to test that your integration works perfectly in my Baxi thermostat, so I would like to ask you for some kind of API documentation or whatever info you have. For the main thermostat control I can take a look to your code (if you don't mind), but I have not any clue about how to get gas consumption data. Would you be able to provide that?

Thanks in advance.

**Comment by msvisser** [comment]
I have added in some API documentation, see [documentation/api.md](https://github.com/msvisser/remeha_home/blob/main/documentation/api.md).

**Comment by vipial1** [comment]
Many thanks! with that documentation I have been able to add consumption data: https://github.com/msvisser/remeha_home/compare/main...vipial1:remeha_home:main

I did not create a pull request because in the same commit (bad decission) I also deleted the binary sensors are they are not useful to me, but probably you want to keep them.

**Comment by msvisser** [comment]
@vipial1 Cool, seems like it was easy enough to add consumption of the last 24h.
It would be great if you could open a PR with these changes, it seems like more people are interested in the energy information after all (see #21 and #24).
Please do remove the changes to the binary sensors, as they should not be necessary.
The binary sensors are disabled by default anyway.
