### ISSUE TITLE
energy consumption

### ISSUE THREAD

**Issue by pj0ttr** [msvisser/remeha_home#24]
Is it possible to add sensors for energy consumption?

**Comment by msvisser** [comment]
As mentioned in #21, for my system the energy usage is not usable at all.
The reported values are wildly inaccurate.
Unless someone actually has a system where the reported values are accurate, I don't see any value in adding the sensors.

If anyone wants to try to add this, there is some information in [documentation/api.md](https://github.com/msvisser/remeha_home/blob/main/documentation/api.md).

**Comment by pj0ttr** [comment]
Hallo, Volgens mij kan het in het Nederlands aan de naam te zien ;)

Ik gebruikte altijd de bdr plugin en daar kon ik de waardes wel uitlezen
alleen die plugin werkt sinds kort niet meer dus.
De waardes wijken indd behoorlijk af en zijn in kwh ipv m3, maar ik kon er
prima uithalen wat het verbruik was tov andere dagen/weken/jaren.

Hopelijk gaat de netbeheerder eindelijk een meer de meter vervangen zodat
die ook de net vervangen slimme gasmeter kan uitlezen en dan is dit niet
meer nodig en kan het via de p1 meter, tot die tijd zou ik echt wel gebruik
willen blijven maken van de kwh waardes uit de remeha.

Dus als het niet teveel moeite is... als je de waarschuwing voor
betrouwbaarheid erbij geeft kunnen mensen denk ik zelf wel bepalen of het
nut voor ze heeft of niet.

Mvg, Peter



Op di 13 jun. 2023 21:43 schreef Michiel Visser ***@***.***>:
