### ISSUE TITLE
Alert Hassio 2023.7.1

### ISSUE THREAD

**Issue by seouk85** [msvisser/remeha_home#27]
Hello, 
updating Home Assistant to version 2023.7.1 this message appears in the system logs:
"Entity None (<class 'custom_components.remeha_home.climate.RemehaHomeClimateEntity'>) is implicitly using device name by not setting its name.Instead, the name should be set to None, please report it to the custom integration author."

Thanks to the availability
Regards Seouk

**Comment by dynasticorpheus** [comment]
Fix in #26

**Comment by seouk85** [comment]
With the suggested fix everything works correctly and there are no anomalies in the log.
Thanks a lot
