### ISSUE TITLE
Readme outdated?

### ISSUE THREAD

**Issue by kokkie-d** [msvisser/remeha_home#28]
In the latest release of Home Assistant I find that the following instructions no longer work: 
**Setup**

1. In Home Assitant click on Configuration
2. Click on Integrations
3. Click on + Add integration
4. Search for and select Remeha Home
5. Enter your email address and password
6. Click "Next"
7. Enjoy

I think the change should be to:

**Setup**

1. In Home Assitant click on Settings
2. Click on Devices & Services --> Devices
3. Click on + Add Device
4. Search for and select Remeha Home
5. Enter your email address and password
6. Click "Next"
7. Enjoy

**Comment by msvisser** [comment]
It looks like it was wrong indeed. I have updated the installation instructions. Thanks!
