### ISSUE TITLE
Usage statistics

### ISSUE THREAD

**Issue by ChristiaanW123** [msvisser/remeha_home#29]
Hi Michiel,

Thanks a lot for this integration, it works really nice for me. I was wondering if it would be possible to include the usage statistics in the integration as an entity. I see they can be obtained using the API you refer to, but they are not in the integration. Unfortunately I'm a nono in programming so I have no idea how to integrate this. Would it be possible to include this in a further update?

My apologies for posting this here as this is not a real "issue" but I didn't know where to post it elsewhere.

**Comment by msvisser** [comment]
Consumption sensors are available in 0.1.14b1 and 0.1.15.
