### ISSUE TITLE
Water temperature Elga Ace

### ISSUE THREAD

**Issue by Tom-Heitbrink** [msvisser/remeha_home#30]
Hello, just migrated from etwist to home app here.
When the Etwist integration was still working it would also return the water temperature of the Elga Ace for the central heating. 
I don't see this in the new app. Is Remeha not delivering this information in the API anymore, or do I need to read a specific value not present in the current output ?

**Comment by msvisser** [comment]
I don't think the new Remeha Home app shows the water temperature, but there is water temperature information in the API, which is available with this integration under the `DHW` device.

**Comment by Tom-Heitbrink** [comment]
I assume those temperatures are for SWW (tapwater) , and what I'm looking for are the delivery and return water temperatures for the heating. I don't see those in the API, so my guess is that they have been removed from the API by Remeha.

**Comment by msvisser** [comment]
I think you are right. Unfortunately, I don't see that information in the responses from the API.
