### ISSUE TITLE
integration failing

### ISSUE THREAD

**Issue by Ilya-Me** [msvisser/remeha_home#32]
Thanks for building this integration.
I was waiting for my swap from the old eTwist app to Remeha home which finally happened today.

However it seems I'm stuck with the integration in Home Assistant.
I am able to login succesfully but it mentions it does not find any devices and "configuration failed, retrying"

If I open the Remeha home app I can see my thermostat and I'm able to change temperature and other settings.

**Comment by msvisser** [comment]
Without more information I cannot really help you. Could you add `_LOGGER.debug("Received data: %s", data)` after line 44 in `coordinator.py` and post the output?

**Comment by Ilya-Me** [comment]
I've been following issue #33 and it seems I also had out of range error. Now with version 13 it is fully operational.
Many thanks!
