### ISSUE TITLE
will De Dietrich work too? 

### ISSUE THREAD

**Issue by jeroenvdd** [msvisser/remeha_home#35]
Hi,
I have a De Dietrich heater,
same app etc as remeha just other brand name,
will this integration work? 

if not could the api address be added for it?

I thought they'd use the same https://api.bdrthermea.net/Mobile/api/ since its the same app / group..
but my login doesn't seem to work for the integration as of now.

**Comment by jeroenvdd** [comment]
well it does seem to work :)
![image](https://github.com/msvisser/remeha_home/assets/6975276/6c45aa4d-71f8-4d4a-bf0f-d02098cc09ae)
Wierdly have everything double but that's for me to find out :)

**Comment by jeroenvdd** [comment]
As an extra but I don't know if the api has it clearly:
could you add gas consumption?

**Comment by alespouzar** [comment]
@jeroenvdd How did you make it work? Did you install and register to Remeha app? Or are you using still De Dietrich login credentials for this Remeha integration? I tried this API with my De Dietrich credentials 2 weeks ago but without success.

**Comment by jeroenvdd** [comment]
> @jeroenvdd How did you make it work? Did you install and register to Remeha app? Or are you using still De Dietrich login credentials for this Remeha integration? I tried this API with my De Dietrich credentials 2 weeks ago but without success.

I just used my de dietrich credentials they worked instantly, never used the remeha app only the 'de dietrich copy'

**Comment by alespouzar** [comment]
I successfully completed OAuth2 authentication process and can now send requests to API (I have my custom scripts, not using Home Assistant). It turns out that De Dietrich works perfectly fine; the only problem a few weeks ago was that I used an old password 🤦
