### ISSUE TITLE
Remeha Home not starting in 2023.11.3

### ISSUE THREAD

**Issue by jdschuitemaker** [msvisser/remeha_home#42]
I just installed version 2023.11.3 and now Remeha Home does not start anymore. 

Anyone else experiencing this issue?

![image](https://github.com/msvisser/remeha_home/assets/2353413/4eee21e0-c2de-45fd-a10f-25cfc267df8b)

Thanks in advance!

**Comment by dimitribo** [comment]
Hello, Also just installed 2023.11.3 and also the same isue ...
![image](https://github.com/msvisser/remeha_home/assets/119052238/7382362a-05eb-4591-824d-ef7efdf54919)

**Comment by schinddo** [comment]
Same issue here.

**Comment by MuadDib007** [comment]
Confirmed issue for me as well. Rollback to HA 2023.11.2 makes it work again.

**Comment by m4v3r1ckNl** [comment]
10-4!

**Comment by timoverwoest** [comment]
Same issue here

**Comment by lajborS** [comment]
Hi, same issue. After rollback to 2023.11.2 - still same situation, integration not working :(

**Comment by MuadDib007** [comment]
It seems the Remeha app itself is also having issues. Perhaps the issue is on their end? My HA has issued again also on 2023.11.2.

**Comment by m4v3r1ckNl** [comment]
> It seems the Remeha app itself is also having issues. Perhaps the issue is on their end? My HA has issued again also on 2023.11.2.

Also having issues with the iOS app, so yes must be at Remeha server side.

**Comment by schinddo** [comment]
Maybe its an issue with the API as the App is also not working properly.

**Comment by msvisser** [comment]
I'm also seeing issues on my on system since about 18:00 last night. Seems like a lot of requests are timing out, but it seems like the app has similar behavior. So most likely this is a problem at the server side. I will keep an eye on it for now.

**Comment by jdschuitemaker** [comment]
It seems that it has been resolved. Could very well be that it was Remeha after all. I am closing this now.

**Comment by jdschuitemaker** [comment]
Solved after Remeha app started working again

**Comment by adebree** [comment]
![image](https://github.com/msvisser/remeha_home/assets/478872/e1f84509-abfb-4415-850f-40777fb9cbe9)
source: https://www.remeha.nl/veelgestelde-vragen/thermostaten/etwist/server-status-etwist

**Comment by m4v3r1ckNl** [comment]
![Screenshot 2023-11-23 at 10 30 44](https://github.com/msvisser/remeha_home/assets/26095980/05184bdb-8832-4fa1-8bed-7b097228374a)

Almost there...
