### ISSUE TITLE
Remeha Home integration stops working with unknown error

### ISSUE THREAD

**Issue by michelvanlaarhoven** [msvisser/remeha_home#43]
Yesterday morning the Remeha Home integration reported new authentication was required. When using the correct username and password it reported an unknown error.
In the meantime I have tried installing different versions of Remeha Home, removing and installing it all resulting in an unknown error.
![Screenshot_20231126_123212_Home Assistant](https://github.com/msvisser/remeha_home/assets/143263908/0cc0b272-0615-4264-816f-359892c06be9)
The Remeha Home app itself is working without any issues.
Any suggestions? Just let me know if you need more information or Log information (and where to get this)

**Comment by michelvanlaarhoven** [comment]
Issue seems to have fixed itself just now.

**Comment by dannyijpelaar** [comment]
I’m having the same problem right now..
