### ISSUE TITLE
Integration can't log in

### ISSUE THREAD

**Issue by dannyij** [msvisser/remeha_home#45]
Since last Sunday, the Rehema Home integration no longer works for me. I can't log in anymore. See screenshot and logging.

![Scherm­afbeelding 2023-11-30 om 11 31 13](https://github.com/msvisser/remeha_home/assets/4631267/d993483e-d359-48b1-82fd-a571775e5cbc)

```
2023-11-30 11:33:43.768 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 293, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 389, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/remeha_home/config_flow.py", line 69, in async_step_auth
    return await self.async_step_creation()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 315, in async_step_creation
    token = await self.flow_impl.async_resolve_external_data(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/remeha_home/api.py", line 246, in async_resolve_external_data
    parsed_callback_url = urllib.parse.urlparse(response.headers["location"])
                                                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'location'
```

Yes, my password is correct. If you log in with incorrect credentials, you'll receive a specific error message for that:

![Scherm­afbeelding 2023-11-30 om 11 32 11](https://github.com/msvisser/remeha_home/assets/4631267/14bcd7e0-a979-4678-84bc-99718baa443c)

I have already removed the integration and reinstalled it, but this makes no difference. I am running Home Assistant version 2023.11.3. The version of the Remeha Home integration is 0.1.13.

**Comment by p2923260** [comment]
Have you tried reverting to 0.13 release?

**Comment by Zwolly-wood** [comment]
I have the same problem for more than a week. The Remeha integration suddenly stops working, reinstall  askes for authentication which is not working. I'm using the latest version of HA and the Remeha integration

**Comment by p2923260** [comment]
If so, I have no clue but please refer to issue #41 . Problems may be started with new beta version 0.14b1. It looks like Remeha site was not able to handle too many pull request. They hung up for some days and then disabled the power measurement also on their App.

**Comment by msvisser** [comment]
Looking at the crash log it seems like the `location` key is missing from the log-in response, which would match the observations of @tkilaaa. I don't think this has anything to do with the 0.1.14 beta versions, as those versions don't have any changes in that specific code. Instead, it is more likely that the authentication API has changed and that we need to handle the response differently.

I would need to have a new look at all the network traffic during the login flow, so it might take some time for me to get to unfortunately.

**Comment by Florian14490** [comment]
Remeha integration Logged out automaticly a  few days ago... i dont know the password anymore but also cannot change it with 'forgot password' 
. I can log in with verification key in Remeha Home app if I click forgot password but can not change it... weird. Anyone had the same and knows a solution to reset passworld?

Hope some can help me or push in right direction.

Thanks Florian

**Comment by LuukvdBeemt** [comment]
I have been having this same issue for the past week, where the response was missing the location key.

Today I got it fixed: I logged out of the remeha home app on my phone (which is the only registered device) and logged in again. After this I could add it to home assistant without any issues.

**Comment by tkilaaa** [comment]
@LuukvdBeemt Yes, that was it.
 I'm not sure, I think the country selection after login was a new dialog?

**Comment by MuadDib007** [comment]
Also solved by doing the logout-login on the Remeha App, and setting Location when asked during login. 
Afterwards login in via HA works again.
Thanks for the workaround / solution

**Comment by martenschukkink** [comment]
No luck for me, I also did the logout-login trick on the app and setting the location when asked. Still no luck with the integration.

When setting up the integration, after inputting my e-mail address and password, I get a blank dialog after a while. I am running HA 2023.12.1 with Remeha Home v0.1.13 on a Home Assistant Green.

![image](https://github.com/msvisser/remeha_home/assets/126795741/19d38988-2ddd-490d-b361-144779c45963)

**Comment by robkor** [comment]
I did the logout and login into the Remeha Home App and set the Location when asked during login.
Afterwards, I logged in on the integration in Home Assistant, and there was no error anymore, and the login worked again.

**Comment by martenschukkink** [comment]
> No luck for me, I also did the logout-login trick on the app and setting the location when asked. Still no luck with the integration.
> 
> When setting up the integration, after inputting my e-mail address and password, I get a blank dialog after a while. I am running HA 2023.12.1 with Remeha Home v0.1.13 on a Home Assistant Green.
> 
> I'm not sure if it is the same issue!?

Retried today and it seems to work now after logging out and in on the app and then logging in the integration

**Comment by danroozemond** [comment]
Same for me, after logging out & in in the app, I could also sign back in Home Assistant. Thanks for the tips :)

**Comment by eldigo** [comment]
Logout and login in the Remeha home app still works to solve the issue with the integration!
👍

**Comment by joene-nl** [comment]
> Logout and login in the Remeha home app still works to solve the issue with the integration! 👍

For me as well!

**Comment by m4v3r1ckNl** [comment]
> Logout and login in the Remeha home app still works to solve the issue with the integration! 👍

+1 here
