### ISSUE TITLE
sensor current temperature

### ISSUE THREAD

**Issue by st4nny** [msvisser/remeha_home#47]
Hi, thank you for this great implementation. 
I haven't found the sensor for the current temperature, that could be useful.

**Comment by dynasticorpheus** [comment]
Create a template based sensor via Settings - Devices & services - Helpers tab - Create Helper

{{ states.**climate.circa**.attributes.current_temperature | float(default=0) }} 

(bold part might have a different name for you)

**Comment by st4nny** [comment]
@dynasticorpheus thank you for suggest!
