### ISSUE TITLE
DeDietrich

### ISSUE THREAD

**Issue by pawelhulek** [msvisser/remeha_home#54]
This integration seems to work with the dedietrich thermostats. 
After logging in to the Remeha app with Dedietrich credentials, the thermostats appear to be discovered automatically. 
It might be worth mentioning this in the description of the integration. I spent quite a bit of time looking for a working integration for dedietrich thermostats, so many others are likely seeking this information as well.

**Comment by mickeyreg** [comment]
I would like to confirm what the author of the issue wrote above :)
The Remeha Home application looks exactly the same as DeDietrich Smart, the only difference is the company logo at the bottom of the page.
I logged in with the same data as for the DeDietrich application and my SmartTC data is read correctly.
I suspect that the app works with all thermostats managed by BDR Thermea Group.

**Comment by Pirionfr** [comment]
I confirm, it's work like charm for me too with my Dedietrich

**Comment by michaelarnauts** [comment]
Same for the Brötje IDA Thermostat with the Brötje Home Komfort App.

I was already reverse engineering the app untill I noticed the call to the api.bdrthermea.net endpoint that directed me to this repository when I searched for it.

**Comment by awhitwam** [comment]
and the same for Baxi! I won't bother doing a fork.  I suspect the references to manufacturer in the API are just for the skin.

**Comment by msvisser** [comment]
I have updated the README to include that this integration will likely work for other brands from the BDR Thermea group.
