### ISSUE TITLE
Debug logging shows an entry that requests to report this

### ISSUE THREAD

**Issue by martienpoels-bank2loyalty** [msvisser/remeha_home#55]
Hi,  I frequently see entries in the log that devices become unavailable, typically when they are controlled by an automation action. This might have something to do with it:
FYI:

Logger: homeassistant.components.climate
Source: components/climate/__init__.py:354
Integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 19:17:56 (1 occurrences)
Last logged: 19:17:56

Entity None (<class 'custom_components.remeha_home.climate.RemehaHomeClimateEntity'>) implements HVACMode(s): off, heat, auto and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/msvisser/remeha_home/issues

**Comment by dynasticorpheus** [comment]
Fixed once #50 is merged
