### ISSUE TITLE
Stopped collecting consumption values

### ISSUE THREAD

**Issue by p2923260** [msvisser/remeha_home#56]
The integration stopped collecting consumed energy since 29th February.
2024-03-02 00:17:52.588 WARNING (MainThread) [custom_components.remeha_home.coordinator] No consumption data found for appliance 2xxxxxxx. Nothing else changed, historical data before 29th still available from the same entity. Also tried restoring a previous backup but the issue still stands.

**Comment by m4v3r1ckNl** [comment]
Leap year date 29-02-2024 causing internal issue(s) on the BDR server?

My logs from 2024-02-29 - 2024-03-02 :

```
This error originated from a custom integration.

Logger: custom_components.remeha_home.coordinator
Source: custom_components/remeha_home/coordinator.py:98
Integration: Remeha Home (documentation, issues)
First occurred: 29 February 2024 at 08:37:51 (210 occurrences)
Last logged: 13:15:18
No consumption data found for appliance 2xxxxx

This error originated from a custom integration.

Logger: custom_components.remeha_home.coordinator
Source: custom_components/remeha_home/coordinator.py:112
Integration: Remeha Home (documentation, issues)
First occurred: 29 February 2024 at 21:40:27 (7 occurrences)
Last logged: 29 February 2024 at 21:54:05

Failed to request consumption data for appliance 2xxxxx: 500, message='Internal Server Error', url=URL('https://api.bdrthermea.net/Mobile/api/appliances/2xxxxx/energyconsumption/daily?startDate=2024-02-29+00:00:00.000000Z&endDate=2024-02-29+23:59:59.000000Z')
```

**Comment by m4v3r1ckNl** [comment]
My Heating Energy Consumed is back up running again. Yesterday I noticed a reset of my Etwist Thermostat as well.

**Comment by p2923260** [comment]
Just to confirm it's ok now. Maybe a glitch server side.

**Comment by p2923260** [comment]
Issue closed as not depending on integration.
