### ISSUE TITLE
Integration is unstable

### ISSUE THREAD

**Issue by ymoona** [msvisser/remeha_home#57]
The problem:
The integration works, but very often the entities become unavailable. 

What have I done to resolve it:
Reinstalled and reconfigured the integration

Environment:
Core 2024.4.4
Supervisor 2024.04.0
Operating System 12.2
Frontend 20240404.2
Remeha Home 0.1.13
HACS 1.34

Part of the logs:
`2024-04-24 10:07:01.113 ERROR (MainThread) [custom_components.remeha_home.coordinator] Timeout fetching remeha_home data
2024-04-24 10:12:02.799 DEBUG (MainThread) [custom_components.remeha_home.coordinator] Finished fetching remeha_home data in 2.688 seconds (success: True)
2024-04-24 10:13:32.112 ERROR (MainThread) [custom_components.remeha_home.coordinator] Timeout fetching remeha_home data
2024-04-24 10:13:32.112 DEBUG (MainThread) [custom_components.remeha_home.coordinator] Finished fetching remeha_home data in 30.002 seconds (success: False)`

**Comment by eldigo** [comment]
Definitely agree on the unavailability part. Especially the past couple of days. But I'm not sure it is the integration.
I think the Remeha home servers are to blame.

My theory is that somehow one of the Remeha server instances goes haywire or the internet connection of the server instance is flapping.
In both cases the integration check every minute for a status update. If you're lucky you get a valid login and all is ok or else you get a login timeout and the entities become unavailable.

Re-installing the integration did not help much for me.

**Comment by joene-nl** [comment]
Same issues here, the entities created by the integration become unavailable every now and then and all of a sudden they are available again.

**Comment by ymoona** [comment]
I have traced the URI and got some more addresses to check.
It seems the API runs Azure.

https://bdriotprdapim.azure-api.net/
https://bdriotprdapim-westeurope-01.regional.azure-api.net

Are now added to the monitor.

**Comment by joene-nl** [comment]
> I have traced the URI and got some more addresses to check. It seems the API runs Azure.
> 
> https://bdriotprdapim.azure-api.net/ https://bdriotprdapim-westeurope-01.regional.azure-api.net
> 
> Are now added to the monitor.


This are the errors I’m getting:
Error requesting remeha_home data: Cannot connect to host api.bdrthermea.net:443 ssl:default [Try again]
Error requesting remeha_home data: Cannot connect to host remehalogin.bdrthermea.net:443 ssl:default [Try again]

**Comment by ymoona** [comment]
Today I was keeping a close eye on the integration and found something I would not expect. When HA reports the thermostat to be unavailable, the app on mobile works fine, including changing the set point. That is not what would have expected.

**Comment by joene-nl** [comment]
Is anyone here using the AdGuard addon for homeassistant? I think that changing the setting described [here](https://github.com/hassio-addons/addon-adguard-home/issues/501) fixed my issues.

**Comment by ymoona** [comment]
I am using AdGuard indeed, I have disabled the "use private reverse DNS resolvers".
Let's see if it this changes anything.

**Comment by ymoona** [comment]
It looks like the integration is now stable.
