### ISSUE TITLE
Control Baxi HybridAPP?

### ISSUE THREAD

**Issue by FezVrasta** [msvisser/remeha_home#67]
Hi, is there a way to support themostats that use the Baxi HybridAPP mobile app? They should all fall under the Baxi thermostats and probably use a very similar API.

I see the app connects to baxi.servitly.com and makes a POST request to `https://baxi.servitly.com/api/identity/users/login?apiKey=xxxx` to login.

```
curl --request POST \
 --url 'https://baxi.servitly.com/api/identity/users/login?apiKey=%2FXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' \
 --header 'accept: application/json, text/plain, */*' \
 --header 'accept-encoding: gzip' \
 --header 'accept-language: en-US,en;q=0.9' \
 --header 'connection: keep-alive' \
 --header 'content-type: application/json' \
 --header 'cookie: foo=bar' \
 --header 'host: baxi.servitly.com' \
 --header 'origin: ionic://wr-app.servitly.com' \
 --header 'sec-fetch-dest: empty' \
 --header 'sec-fetch-mode: cors' \
 --header 'sec-fetch-site: cross-site' \
 --header 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148' \
 --header 'x-semioty-tenant: baxi' \
 --cookie foo=bar \
 --data '{"email":"....","password":"...","devices":[{"deviceId":"XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","model":"iPad8,6","platform":"iOS","platformVersion":"17.5","browser":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148"}]}'
```

**Comment by cudiz27** [comment]
Hi, I am interessed too if you find a way to get it working, thx!

**Comment by FezVrasta** [comment]
It's the thermostat of a rented house that I'll leave soon so I don't think I'll spend time finding a way to integrate it unfortunately.

**Comment by msvisser** [comment]
Unfortunately I think this is a completely different product range, which uses a different app than the Remeha Home, or Baxi equivalent. Therefore I don't think I'm going to support it in this integration. If anyone can confirm that this app also uses `https://api.bdrthermea.net/Mobile/api/`, then I will have a look at it.

**Comment by Cm-8** [comment]
@FezVrasta @cudiz27 
I've been working on it, do you want to try this integration?

https://github.com/Cm-8/baxi_hybridapp_home/
