### ISSUE TITLE
It works with BAXI & DeDietrich thermostats

### ISSUE THREAD

**Issue by awhitwam** [msvisser/remeha_home#69]
You should update your readme file to mention it works with these manufacturers with no modifications.

All the mobile Apps are the same (just a different skin) and they all accept the same login credentials.

For example, I have a BAXI system but the Remeha and DeDietrich both do exactly the same job

**Comment by msvisser** [comment]
I have added some information in the README that this will also work with other BDR Thermea Group brands.
