### ISSUE TITLE
Feature request: Enable/Disable fireplace mode

### ISSUE THREAD

**Issue by lobernat** [msvisser/remeha_home#7]
Hello, 

With the wood fire pit on, the fire tricks the temperature of the thermostat and shutdown the boiler as a consequence the rest of the rooms of the house gets cold.

If home assistant can control the fireplacemode it can enable and disable with and automation like if the room temperature is above 3degres of the average of the rooms enable fireplace mode.

Thanks 👍

**Comment by msvisser** [comment]
Fireplace mode is something that looks like it is supported in the new Remeha Home app, so I will look into supporting it in this integration.

**Comment by msvisser** [comment]
In the [latest commit](https://github.com/msvisser/remeha_home/commit/479468c421142c8578b446687e92af9458e54f64) on main I have added in a switch for the fireplace mode.

Let me know if this does what you expect.
