### ISSUE TITLE
Help with new proyect?

### ISSUE THREAD

**Issue by Imanol82** [msvisser/remeha_home#70]
Hello,

I am integrating the Baxi (Remeha, Dietrich) aerothermal system into Home Assistant without having to use the Cloud. All by Modbus and ESPHome.

I have already configured the DHW entities but I am having a hard time integrating them into a Climate type entity like yours. 
My idea is to create 2 Climate entities, one for the DWH and the other for heating/cooling.

I have started from DHW,

I leave you the link of the post in case you want to help me, the truth is that I would greatly appreciate it.

Thank you very much!!!

[https://community.home-assistant.io/t/baxi-remeha-dietrich-to-esp32-with-esphome/777548](url)

**Comment by msvisser** [comment]
Hi, thank you for sharing your project! Unfortunately, I don't really have time to work on more projects. Also, your project is a completely different approach to integrating the boiler/thermostat, so I don't know if I can be of much help.

**Comment by Imanol82** [comment]
What a shame, I think it would be interesting to stop depending on Cloud and do everything locally.

My question is the thermostat, I'm not sure I can create a thermostat like yours, but hey, I'll keep trying.

Thank you very much and good job with your project!
