### ISSUE TITLE
Timeout fetching remeha_home data

### ISSUE THREAD

**Issue by kranendijk** [msvisser/remeha_home#73]
Checking the log, I see this error repeatedly. I do not know if it is serious or not, as the integration  seems to work. However I think it is worh noting and investigating?

`Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.remeha_home.coordinator
Bron: helpers/update_coordinator.py:360
integratie: Remeha Home (documentatie, problemen)
Eerst voorgekomen: 6 oktober 2024 om 11:43:46 (33 gebeurtenissen)
Laatst gelogd: 11:18:39

Timeout fetching remeha_home data `

**Comment by msvisser** [comment]
This is not an issue with your specific setup of the integration. It just seems that the API sometimes does not respond within 30 seconds. The behavior is not really consistent, as I can sometimes go days without any errors, and then have days where I get a lot of them.

I don't think I can really do anything to fix this problem, so for now we just have to live with a bit of flakiness.
