### ISSUE TITLE
Warning “ No consumption data found for appliance xyz”

### ISSUE THREAD

**Issue by kranendijk** [msvisser/remeha_home#74]
Hi,

No error but a warning in my Home Assistant for this integration. I am puzzling on where (which device) it is coming from. Can you please tell me where to look so I can clean it and prevent the warning message? It happens every day and I cannot find where it is coming from.

Thanks!!

Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.remeha_home.coordinator
Bron: custom_components/remeha_home/coordinator.py:99
integratie: Remeha Home (documentatie, problemen)
Eerst voorgekomen: 2 november 2024 om 00:08:30 (16 gebeurtenissen)
Laatst gelogd: 01:54:07

No consumption data found for appliance d9ea262d-cc8f-4f4d-bd30-12e864997335

**Comment by msvisser** [comment]
You can ignore this warning. The API does not report consumption data during the first 1-2 hours of the day, which triggers the warning, but by now I'm pretty sure this happens for everyone, so I will remove the warning in the next update.
