### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by HanSyt** [msvisser/remeha_home#8]
I was transferred from the etwist to the home app. I used BDR thermostat and luckily I found this integration. Is it possible to add water temperature lik there was in BDR thermostat. I used this to monitor if I can eventually switch to a Hybride solution. Water temperature in heating modus should not be higher than 50.

Thanks.

**Comment by the-little-wave** [comment]
+1 for this. I found monitoring water temperature really useful and came to this integration from the Baxi integration that's recently stopped working ( https://community.home-assistant.io/t/baxi-txm-rxm-10c-opentherm-thermostat-ha-integration/358612 ). I think it was referred to as "flow temperature" there.

Thanks.

**Comment by dynasticorpheus** [comment]
+1 however last time I checked the new API is no longer exposing this value.

**Comment by msvisser** [comment]
As these other people were saying, I don't think this value is actually exposed by the new API. The only water temperature I can see in the API is the water temperature of the hot water heater, but not of the central heating.

Maybe have a look at [this comment](https://github.com/msvisser/remeha_home/issues/6#issuecomment-1428524447) I made in another issue and let me know if you see a value that you think is the correct one.

**Comment by Gyosa3** [comment]
It may be this value:
`'dhwTemperature': 27.7,`
The fact that it's located in the "hot water" section does not necessarily mean that it is not also the one for the central heating circuit, as they pass through the same heater sort to say.

On my boiler the internal temp shows in the front display, and it goes up whichever function is activated, central heating or hot water, so I'd give it a try in absence of any better shot.

**Comment by HanSyt** [comment]
To be quite honest, I think [Gyosa3](https://github.com/Gyosa3) is right. In my old BDR Thermostat plugin, temperature of the boiler and heating was in 1 graph. I could see my showering, temperature running up tot 65 degrees, rest of the day between 20-40.

**Comment by msvisser** [comment]
I've added in a sensor for the `dhwTemperature`. Let me know if it's what you expected.

**Comment by HanSyt** [comment]
Thanks Michel,

Imported the new code in Home Assistant and added sensor and history graph. Now waiting to see what happens during the day.

**Comment by HanSyt** [comment]
It looks good, just like the old water temperature sensor in etwist. You can see modulation and the moment just before 1900 when I used hot water from the boiler.

![image](https://user-images.githubusercontent.com/56794786/221377510-dc16ac84-b78a-4614-9979-5c0fe7ae534a.png)
