### ISSUE TITLE
Water temperatuur niet zichtbaar

### ISSUE THREAD

**Issue by Qoen1** [msvisser/remeha_home#80]
Ik kan de water temperatuur niet zien in de home assistant app. Ik kan hem echter ook niet zien in de Remeha home app. Hoort dat wel te kunnen? Ik kan dat nergens vinden.

**Comment by DaanSelen** [comment]
> Ik kan de water temperatuur niet zien in de home assistant app. Ik kan hem echter ook niet zien in de Remeha home app. Hoort dat wel te kunnen? Ik kan dat nergens vinden.

Ik denk dat als de Remeha app het zelf niet laat zien dat het wellicht niet door de ketel wordt verstuurd.

**Comment by msvisser** [comment]
Helaas wordt deze informatie niet meer aangeboden vanuit de API, dus kan deze integratie dat ook niet laten zien.

**Comment by michaelarnauts** [comment]
@msvisser Ik kan het nog steeds zien, zowel in de App als in Home Assistant.

Ik gebruik de Brötje Home Comfort App (maar die lijkt quasi hetzelfde te zijn met de Remeha Home app, en daar zie ik ook de watertemperatuur).
