### ISSUE TITLE
Target Temperature Feature does not apply

### ISSUE THREAD

**Issue by DaanSelen** [msvisser/remeha_home#81]
Setting it up:

![image](https://github.com/user-attachments/assets/f38bfa9e-950c-4638-8a0a-6a36b7cb33d3)

Set a new Target:

![image](https://github.com/user-attachments/assets/e0b89c76-f699-4ea2-a71d-709ac9b9c82a)

Refresh:

![image](https://github.com/user-attachments/assets/57782bab-50dc-4d36-80c5-bae16d26d489)

How come this happends?

**Comment by michaelarnauts** [comment]
I think this is the cause: https://github.com/msvisser/remeha_home/pull/78

**Comment by DaanSelen** [comment]
> I think this is the cause: https://github.com/msvisser/remeha_home/pull/78

Yes
